---
swagger: "2.0"
info:
  description: "更多 Spring Boot 相关文章 http://www.ymq.io"
  version: "V1"
  title: "Spring Boot 中使用 Swagger2构建 RESTful API 文档"
  termsOfService: "http://www.ymq.io"
tags:
- name: "YmqController 测试"
  description: "RESTful API"
schemes:
- "http"
paths:
  /user/{id}:
    get:
      tags:
      - "YmqController 测试"
      summary: "获取用户详细信息"
      description: "根据url的id来获取用户详细信息"
      operationId: "getUser"
      parameters:
      - name: ""
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
    put:
      tags:
      - "YmqController 测试"
      summary: "更新用户详细信息"
      description: "根据url的id来指定更新对象，并根据传过来的user信息来更新用户详细信息"
      operationId: "putUser"
      parameters:
      - name: ""
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
    delete:
      tags:
      - "YmqController 测试"
      summary: "删除用户"
      description: "根据url的id来指定删除对象"
      operationId: "deleteUser"
      parameters:
      - name: ""
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
definitions:
  User:
    type: "object"
    required:
    - "age"
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "id"
      name:
        type: "string"
        description: "姓名"
      age:
        type: "integer"
        format: "int32"
        description: "年龄"
    description: "请求入参 User "
