---
swagger: "2.0"
info:
  description: "更多 Spring Boot 相关文章 http://www.ymq.io"
  version: "V3"
  title: "io.ymq.swagger.controller"
  termsOfService: "http://www.ecej.com/"
tags:
- name: "YmqController 测试"
  description: "RESTful API"
schemes:
- "http"
paths:
  /getUserList:
    get:
      tags:
      - "YmqController 测试"
      summary: "获取用户列表"
      description: ""
      operationId: "getUserList"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
